# Generated by Django 5.2.4 on 2025-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TextAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The medical text to be annotated"),
                ),
                (
                    "drugs",
                    models.JSONField(
                        default=list, help_text="List of drugs mentioned in the text"
                    ),
                ),
                (
                    "adverse_events",
                    models.JSONField(
                        default=list,
                        help_text="List of adverse events mentioned in the text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this annotation has been validated",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
