# Generated by Django 5.2.4 on 2025-07-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textannotation",
            name="adverse_events",
        ),
        migrations.RemoveField(
            model_name="textannotation",
            name="drugs",
        ),
        migrations.AddField(
            model_name="textannotation",
            name="entities",
            field=models.JSONField(
                default=list,
                help_text="List of annotated entities (text, start, end, label)",
            ),
        ),
    ]
