# Generated by Django 5.2.4 on 2025-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_remove_textannotation_adverse_events_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textannotation",
            name="entities",
        ),
        migrations.AddField(
            model_name="textannotation",
            name="adverse_events",
            field=models.JSONField(
                default=list, help_text="List of adverse events mentioned in the text"
            ),
        ),
        migrations.AddField(
            model_name="textannotation",
            name="drugs",
            field=models.JSONField(
                default=list, help_text="List of drugs mentioned in the text"
            ),
        ),
    ]
