# Generated by Django 5.2.4 on 2025-07-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_remove_textannotation_entities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textannotation",
            name="adverse_events",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of adverse events mentioned in the text",
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="drugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of drugs mentioned in the text",
            ),
        ),
        migrations.CreateModel(
            name="AnnotationChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("drug_added", "Drug Added"),
                            ("drug_removed", "Drug Removed"),
                            ("drug_bulk_update", "Drugs Bulk Update"),
                            ("adverse_event_added", "Adverse Event Added"),
                            ("adverse_event_removed", "Adverse Event Removed"),
                            ("adverse_event_bulk_update", "Adverse Events Bulk Update"),
                            ("validated", "Marked as Validated"),
                            ("unvalidated", "Marked as Unvalidated"),
                            ("annotation_created", "Annotation Created"),
                            ("annotation_imported", "Annotation Imported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="annotation.textannotation",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["annotation", "-timestamp"],
                        name="annotation__annotat_e97c79_idx",
                    ),
                    models.Index(
                        fields=["change_type", "-timestamp"],
                        name="annotation__change__e01e7f_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="annotation__timesta_b03238_idx"
                    ),
                ],
            },
        ),
    ]
