# Generated by Django 5.2.4 on 2025-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_alter_textannotation_adverse_events_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="annotationchange",
            name="annotation__annotat_e97c79_idx",
        ),
        migrations.RemoveIndex(
            model_name="annotationchange",
            name="annotation__change__e01e7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="annotationchange",
            name="annotation__timesta_b03238_idx",
        ),
        migrations.RemoveField(
            model_name="annotationchange",
            name="details",
        ),
        migrations.RemoveField(
            model_name="annotationchange",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="annotationchange",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="annotationchange",
            name="entity_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the entity that was added/removed",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="annotationchange",
            name="field_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the field that was changed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annotationchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("drug_added", "Drug Added"),
                    ("drug_removed", "Drug Removed"),
                    ("event_added", "Adverse Event Added"),
                    ("event_removed", "Adverse Event Removed"),
                    ("validation_changed", "Validation Status Changed"),
                    ("bulk_update", "Bulk Update"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="annotationchange",
            name="new_value",
            field=models.JSONField(blank=True, help_text="New value", null=True),
        ),
        migrations.AlterField(
            model_name="annotationchange",
            name="old_value",
            field=models.JSONField(blank=True, help_text="Previous value", null=True),
        ),
        migrations.AlterField(
            model_name="annotationchange",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Browser session ID for tracking user sessions",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="adverse_events",
            field=models.JSONField(
                default=list, help_text="List of adverse events mentioned in the text"
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="drugs",
            field=models.JSONField(
                default=list, help_text="List of drugs mentioned in the text"
            ),
        ),
    ]
