# Generated by Django 5.2.4 on 2025-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotation",
            "0005_remove_annotationchange_annotation__annotat_e97c79_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("drug_added", "Drug Added"),
                    ("drug_removed", "Drug Removed"),
                    ("event_added", "Adverse Event Added"),
                    ("event_removed", "Adverse Event Removed"),
                    ("bulk_update", "Bulk Update"),
                ],
                max_length=20,
            ),
        ),
    ]
