# Generated by Django 5.2.4 on 2025-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0006_alter_annotationchange_change_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADEListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrugListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
