# Generated by Django 5.2.4 on 2025-07-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0007_adelistentry_druglistentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the entity type (e.g., 'drugs', 'adverse_events', 'persons', 'locations')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the entity type",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this entity type represents",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for this entity type",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entity type is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="annotationchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("drug_added", "Drug Added"),
                    ("drug_removed", "Drug Removed"),
                    ("event_added", "Adverse Event Added"),
                    ("event_removed", "Adverse Event Removed"),
                    ("entity_added", "Entity Added"),
                    ("entity_removed", "Entity Removed"),
                    ("entity_modified", "Entity Modified"),
                    ("bulk_update", "Bulk Update"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="adverse_events",
            field=models.JSONField(
                default=list,
                help_text="List of adverse events mentioned in the text (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="drugs",
            field=models.JSONField(
                default=list, help_text="List of drugs mentioned in the text (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="text",
            field=models.TextField(help_text="The text to be annotated"),
        ),
        migrations.AddField(
            model_name="annotationchange",
            name="entity_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of entity that was changed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="annotation.entitytype",
            ),
        ),
        migrations.CreateModel(
            name="EntityListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the entity", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="annotation.entitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("entity_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="EntityAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Name of the annotated entity", max_length=255
                    ),
                ),
                (
                    "start_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Character position where entity starts",
                        null=True,
                    ),
                ),
                (
                    "end_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Character position where entity ends",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence score for this annotation (0.0-1.0)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text_annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_annotations",
                        to="annotation.textannotation",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="annotation.entitytype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_position", "entity_name"],
                "unique_together": {
                    (
                        "text_annotation",
                        "entity_type",
                        "entity_name",
                        "start_position",
                        "end_position",
                    )
                },
            },
        ),
    ]
